require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe InvoicesController, type: :controller do

  let(:client) { FactoryBot.create(:client)}
  let(:user) {FactoryBot.create(:user)}

  before(:each) do
    log_in_as(user)
  end

  # This should return the minimal set of attributes required to create a valid
  # Invoice. As you add validations to Invoice, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {
      :user_id => user.id,
      :client_id => client.id,
      :issue_date => "2017-11-26 11:02:23",
      :total_amount => "9.99"
    }
  }

  let(:invalid_attributes) { {
      :issue_date => "2017-11-26 11:02:23",
      :total_amount => "9.99"
    }
  }

  describe "GET #index" do
    it "returns a success response" do
      invoice = Invoice.create! valid_attributes
      get :index, params: {}
      expect(response).to be_success
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      invoice = Invoice.create! valid_attributes
      get :show, params: {id: invoice.to_param}
      expect(response).to be_success
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}
      expect(response).to be_success
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      invoice = Invoice.create! valid_attributes
      get :edit, params: {id: invoice.to_param}
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Invoice" do
        expect {
          post :create, params: {invoice: valid_attributes}
        }.to change(Invoice, :count).by(1)
      end

      it "redirects to the created invoice" do
        post :create, params: {invoice: valid_attributes}
        expect(response).to redirect_to(Invoice.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {invoice: invalid_attributes}
        expect(response).to be_success
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested invoice" do
      invoice = Invoice.create! valid_attributes
      expect {
        delete :destroy, params: {id: invoice.to_param}
      }.to change(Invoice, :count).by(-1)
    end

    it "redirects to the invoices list" do
      invoice = Invoice.create! valid_attributes
      delete :destroy, params: {id: invoice.to_param}
      expect(response).to redirect_to(invoices_url)
    end
  end

end
